#!/bin/bash
# setup-full.sh -- Deploy gh-bootstrap + self-hosted ntfy on Uberspace
#
# Prerequisites:
#   - Uberspace account with SSH access
#   - GitHub fine-grained PAT (repo create + contents write)
#
# Usage:
#   1. Edit the CONFIG section below
#   2. scp this file + gh-bootstrap.js to your Uberspace
#   3. ssh you@host.uberspace.de
#   4. bash setup-full.sh
#
# Layout:
#   ~/gh-bootstrap/          -> Node.js API server (port 9876)
#   ~/ntfy/                  -> ntfy binary + config (port 8008)
#   ~/etc/services.d/*.ini   -> supervisord configs
#
# Web routing:
#   /gh/*  -> gh-bootstrap (port 9876)
#   /*     -> ntfy          (port 8008)

set -euo pipefail
trap 'echo "Failed at line $LINENO"; exit 1' ERR

# -- CONFIG (edit these!) --
NTFY_VERSION="2.17.0"
NTFY_PORT=8008
NTFY_ADMIN_USER="admin"
NTFY_ADMIN_PASS="CHANGE_ME_ntfy_admin_pass"
NTFY_TOPIC="gh-bootstrap"

GH_PORT=9876
GITHUB_PAT="ghp_CHANGE_ME"
GITHUB_OWNER="ManuelKugelmann"
AUTH_USER="CHANGE_ME_api_user"
AUTH_PASS="CHANGE_ME_api_pass"
DAILY_LIMIT=15

HOST=$(hostname)
BASE_URL="https://${HOST}"
C_RED='\033[0;31m'; C_GRN='\033[0;32m'; C_YEL='\033[0;33m'; C_CYN='\033[0;36m'; C_RST='\033[0m'

log()  { echo -e "${C_CYN}>${C_RST} $*"; }
ok()   { echo -e "${C_GRN}ok${C_RST} $*"; }
warn() { echo -e "${C_YEL}warn${C_RST} $*"; }
die()  { echo -e "${C_RED}error${C_RST} $*" >&2; exit 1; }

# -- Preflight checks --
[[ "$GITHUB_PAT" == "ghp_CHANGE_ME" ]] && die "Edit CONFIG section first! GITHUB_PAT not set."
[[ "$AUTH_PASS" == "CHANGE_ME_api_pass" ]] && die "Edit CONFIG section first! AUTH_PASS not set."
[[ "$NTFY_ADMIN_PASS" == "CHANGE_ME_ntfy_admin_pass" ]] && die "Edit CONFIG section first! NTFY_ADMIN_PASS not set."

command -v node >/dev/null || die "Node.js not found. Run: uberspace tools version use node 22"
command -v supervisorctl >/dev/null || die "supervisorctl not found"
mkdir -p ~/etc/services.d

# PART 1: ntfy

log "Installing ntfy v${NTFY_VERSION}..."
mkdir -p ~/ntfy

if [[ ! -x ~/ntfy/ntfy ]] || [[ "$(~/ntfy/ntfy --version 2>/dev/null || true)" != *"${NTFY_VERSION}"* ]]; then
  TARBALL="ntfy_${NTFY_VERSION}_linux_amd64.tar.gz"
  wget -q -O "/tmp/${TARBALL}" \
    "https://github.com/binwiederhier/ntfy/releases/download/v${NTFY_VERSION}/${TARBALL}" \
    || die "Failed to download ntfy v${NTFY_VERSION}"
  tar --strip-components=1 -xzf "/tmp/${TARBALL}" -C ~/ntfy/
  rm -f "/tmp/${TARBALL}"
  ok "ntfy binary installed"
else
  ok "ntfy v${NTFY_VERSION} already installed"
fi

log "Writing ntfy server config..."
cat > ~/ntfy/server.yml << NTFYEOF
# ntfy server config -- generated by setup-full.sh
base-url: ${BASE_URL}
listen-http: ":${NTFY_PORT}"
behind-proxy: true

# Storage
cache-file: "${HOME}/ntfy/cache.db"
cache-duration: "12h"

# Auth -- deny by default, require login
auth-file: "${HOME}/ntfy/auth.db"
auth-default-access: "deny-all"

# Attachments
attachment-cache-dir: "${HOME}/ntfy/attachments"
attachment-total-size-limit: "100M"
attachment-file-size-limit: "1M"
attachment-expiry-duration: "3h"

# Connection tuning (Uberspace reverse proxy)
keepalive-interval: "45s"
manager-interval: "2m"

# Web UI at root
web-root: /

# Limits
visitor-subscription-limit: 30

log-level: INFO
NTFYEOF
ok "ntfy config written"

log "Configuring ntfy admin user..."
~/ntfy/ntfy user --config ~/ntfy/server.yml del "${NTFY_ADMIN_USER}" 2>/dev/null || true
~/ntfy/ntfy user --config ~/ntfy/server.yml add --role=admin "${NTFY_ADMIN_USER}" <<< "$(printf '%s\n%s\n' "${NTFY_ADMIN_PASS}" "${NTFY_ADMIN_PASS}")"
ok "ntfy admin user '${NTFY_ADMIN_USER}' configured"

log "Creating ntfy access token for gh-bootstrap..."
NTFY_TOKEN=$(~/ntfy/ntfy token --config ~/ntfy/server.yml add "${NTFY_ADMIN_USER}" 2>&1 | grep -oP 'tk_\S+' || true)
if [[ -z "$NTFY_TOKEN" ]]; then
  warn "Could not extract token. List existing tokens:"
  ~/ntfy/ntfy token --config ~/ntfy/server.yml list 2>&1 || true
  warn "Set NTFY_TOKEN manually in the gh-bootstrap.ini if needed."
  NTFY_TOKEN="MANUAL_SET_REQUIRED"
else
  ok "ntfy token: ${NTFY_TOKEN}"
fi

log "Writing ntfy supervisord config..."
cat > ~/etc/services.d/ntfy.ini << EOF
[program:ntfy]
command=%(ENV_HOME)s/ntfy/ntfy serve --config %(ENV_HOME)s/ntfy/server.yml
autostart=true
autorestart=true
startsecs=5
EOF
ok "ntfy.ini written"

# PART 2: gh-bootstrap

log "Setting up gh-bootstrap..."
mkdir -p ~/gh-bootstrap

if [[ ! -f ~/gh-bootstrap/gh-bootstrap.js ]]; then
  if [[ -f ./gh-bootstrap.js ]]; then
    cp ./gh-bootstrap.js ~/gh-bootstrap/
    ok "Copied gh-bootstrap.js from current directory"
  else
    die "gh-bootstrap.js not found! Place it next to this script or in ~/gh-bootstrap/"
  fi
else
  ok "gh-bootstrap.js already in place"
fi

# Ensure ESM
if [[ ! -f ~/gh-bootstrap/package.json ]]; then
  cat > ~/gh-bootstrap/package.json << 'EOF'
{ "type": "module" }
EOF
  ok "package.json created (ESM)"
fi

log "Writing gh-bootstrap supervisord config..."
cat > ~/etc/services.d/gh-bootstrap.ini << EOF
[program:gh-bootstrap]
directory=%(ENV_HOME)s/gh-bootstrap
command=node %(ENV_HOME)s/gh-bootstrap/gh-bootstrap.js
autostart=true
autorestart=true
startsecs=5
environment=
    GITHUB_PAT="${GITHUB_PAT}",
    GITHUB_OWNER="${GITHUB_OWNER}",
    AUTH_USER="${AUTH_USER}",
    AUTH_PASS="${AUTH_PASS}",
    PORT="${GH_PORT}",
    DAILY_LIMIT="${DAILY_LIMIT}",
    NTFY_URL="http://localhost:${NTFY_PORT}",
    NTFY_TOPIC="${NTFY_TOPIC}",
    NTFY_TOKEN="${NTFY_TOKEN}"
EOF
ok "gh-bootstrap.ini written"

# PART 3: Web backends

log "Registering web backends..."
uberspace web backend set /gh --http --port ${GH_PORT} 2>/dev/null || true
uberspace web backend set / --http --port ${NTFY_PORT} 2>/dev/null || true
ok "Web backends registered"

echo ""
log "Current web backends:"
uberspace web backend list

# PART 4: Start services

log "Starting services..."
supervisorctl reread
supervisorctl update

supervisorctl stop ntfy 2>/dev/null || true
supervisorctl stop gh-bootstrap 2>/dev/null || true
sleep 1
supervisorctl start ntfy
sleep 2
supervisorctl start gh-bootstrap
sleep 2

echo ""
log "Service status:"
supervisorctl status ntfy gh-bootstrap

# PART 5: Verification

echo ""
echo -e "${C_CYN}--- Verification ---${C_RST}"

log "Testing ntfy health..."
NTFY_HEALTH=$(curl -sf "http://localhost:${NTFY_PORT}/v1/health" 2>/dev/null || echo "FAIL")
if echo "$NTFY_HEALTH" | grep -q "healthy"; then
  ok "ntfy healthy"
else
  warn "ntfy health check: ${NTFY_HEALTH}"
fi

log "Testing gh-bootstrap status..."
GH_STATUS=$(curl -sf "http://localhost:${GH_PORT}/gh/status" 2>/dev/null || echo "FAIL")
if echo "$GH_STATUS" | grep -q '"ok":true'; then
  ok "gh-bootstrap healthy: ${GH_STATUS}"
else
  warn "gh-bootstrap status: ${GH_STATUS}"
fi

log "Sending test notification..."
curl -sf \
  -H "Authorization: Bearer ${NTFY_TOKEN}" \
  -H "Title: Setup Complete" \
  -H "Tags: white_check_mark" \
  -d "gh-bootstrap + ntfy deployed on ${HOST}" \
  "http://localhost:${NTFY_PORT}/${NTFY_TOPIC}" >/dev/null 2>&1 \
  && ok "Test notification sent to topic '${NTFY_TOPIC}'" \
  || warn "Test notification failed (token may need manual setup)"

# Summary

echo ""
echo -e "${C_GRN}--- Setup Complete ---${C_RST}"
echo ""
echo -e "  ${C_CYN}ntfy web UI:${C_RST}       ${BASE_URL}"
echo -e "  ${C_CYN}ntfy topic:${C_RST}        ${BASE_URL}/${NTFY_TOPIC}"
echo -e "  ${C_CYN}gh-bootstrap API:${C_RST}  ${BASE_URL}/gh/bootstrap"
echo -e "  ${C_CYN}gh-bootstrap status:${C_RST} ${BASE_URL}/gh/status"
echo ""
echo -e "  ${C_YEL}Android app setup:${C_RST}"
echo -e "    1. Install ntfy from Play Store / F-Droid"
echo -e "    2. Settings -> Default server -> ${BASE_URL}"
echo -e "    3. Settings -> Manage users -> Add: ${NTFY_ADMIN_USER} / (your password)"
echo -e "    4. Subscribe to topic: ${NTFY_TOPIC}"
echo ""
echo -e "  ${C_YEL}Usage from Claude Chat:${C_RST}"
echo -e "    curl -s -u ${AUTH_USER}:****  ${BASE_URL}/gh/bootstrap \\"
echo -e "      -H 'Content-Type: application/json' \\"
echo -e "      -d '{\"name\":\"my-project\",\"claude_md\":\"# my-project\\n...\"}'"
echo ""
echo -e "  ${C_YEL}Logs:${C_RST}"
echo -e "    supervisorctl tail -f ntfy"
echo -e "    supervisorctl tail -f gh-bootstrap"
echo ""

if [[ "$NTFY_TOKEN" == "MANUAL_SET_REQUIRED" ]]; then
  echo -e "${C_RED}NTFY_TOKEN extraction failed.${C_RST}"
  echo -e "  Run: ~/ntfy/ntfy token --config ~/ntfy/server.yml list"
  echo -e "  Then update NTFY_TOKEN in ~/etc/services.d/gh-bootstrap.ini"
  echo -e "  Then: supervisorctl restart gh-bootstrap"
fi
